export const FIND_ALL_USER = 'FIND_ALL_USER'
export const FIND_ALL_USER_FAILURE = 'FIND_ALL_USER_FAILURE'

export const FIND_USER_BY_ID = 'FIND_USER_BY_ID'
export const FIND_USER_BY_ID_FAILURE  = 'FIND_USER_BY_ID_FAILURE'

export const FIND_IMG_BY_ID = 'FIND_IMG_BY_ID'
export const FIND_IMG_BY_ID_FAILURE  = 'FIND_IMG_BY_ID_FAILURE'
